### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Phoenix1747** [midspace/SEToolbox#114]
Is there a way to help translate this program? I didn't find any specific folder like "i18n".

**Comment by midspace** [comment]
For all details see https://github.com/midspace/SEToolbox/issues/21

Translation probably requires a community effort, as there are hundreds of strings to be translated.
The application uses resources, which have been set up.
Currently the only part missing is adding the deployment of the SEToolboxUpdate satellite resources to the build script, otherwise everything is ready for additional languages.

See the Resources.resx in the below folders for all strings to be translated.
See the Resources.zh.resx as a sample I was using to test with Chinese localization.

https://github.com/midspace/SEToolbox/tree/master/Main/SEToolbox/SEToolbox/Properties
https://github.com/midspace/SEToolbox/tree/master/Main/SEToolbox/SEToolboxUpdate/Properties

**Comment by Phoenix1747** [comment]
Great, thanks!

**Comment by midspace** [comment]
@Phoenix1747  Is there a specific language you would like to see first?

**Comment by Phoenix1747** [comment]
Personally, I'd contribute to German, but I don't have any specific preferences.

**Comment by midspace** [comment]
Ackuna project set up for German:
https://ackuna.com/translate-/space-engineers-toolbox/at-a-glance/german
