### ISSUE TITLE
Saved Game broken??

### ISSUE THREAD

**Issue by Morketh** [midspace/SEToolbox#118]
When trying to place a conveyor on a conveyor junction SE will crash to desktop. So figuring this might be a simple Toolbox fix i loaded up the tool box selected my saved game and promptly hit repair. After chugging along for several minutes the tool box crashes and reports back with "Object reference not set to an instance of an object"
![setoolbox_2017-12-06_16-14-18](https://user-images.githubusercontent.com/6291631/33690518-1bbf8274-daa1-11e7-8e56-23466b85bc2a.png)

Game save is available if needed for debugging.

**Comment by midspace** [comment]
More than likely SEToolbox cannot help you with the crash to desktop with the game,
but sending me a copy of the world will help me identify what caused SEToolbox to crash.

**Comment by Morketh** [comment]
Saved game file can be found [here](https://puu.sh/yB9lH/4cc3791718.7z)
Steps to reproduce crash are as follows:
Spawn at the Medical Room owned by Nobody.
Underneath the landing pad there is 2 Conveyor Junction blocks. Placing a Conveyor tube on the block with the vertical tube will result in an instant crash to desktop.
Oddly enough once the station was set to Nobody as the owner i was unable to reproduce the crash.

**Comment by midspace** [comment]
I haven't been able to reproduce either issue.
Crashing the game, or SEToolbox.

I was guessing prior to this, the issue with SEToolbox would most likely be caused by a mod. Some of the older mods have given me a few issues, and now finding how many mods you have in the world I'm pretty certain now.

SEToolbox should have written a copy of the error to the Event Log.
Would you be able to retrieve a copy?
I have instructions here on how to find it.
https://github.com/midspace/SEToolbox/wiki/Reporting-bugs

**Comment by Morketh** [comment]
[SEToolbox Crashreport 12-7-17.txt](https://github.com/midspace/SEToolbox/files/1539576/SEToolbox.Crashreport.12-7-17.txt)

**Comment by midspace** [comment]
Thanks for that Morketh.
It looks like I've accidentally fixed that issue in this recent Toolbox release in the following set of changes https://github.com/midspace/SEToolbox/commit/9fb2f25164948483212e600dd95a23ef199b958a

I've just removed some old code which is no longer needed in the Repair.

**Comment by midspace** [comment]
Dumping crash logs to the install directory is impossible due to how Windows applies security to the Program Files directory.
Individually, you might be able to turn off UAC and other security to allow a program to write a file there, but other users won't necessarily know how to do that, or allow their computer to be so insecure.

Writing an EventLog to the Application log has been by far the most compatible method.
