### ISSUE TITLE
SEToolbox 01.119.005 Release 1

### ISSUE THREAD

**Issue by Amberyl56** [midspace/SEToolbox#47]
Just downloaded and not responding

**Comment by midspace** [comment]
Could you please provide more details on what is not responding?

Did you download the .zip or the .msi file?
https://github.com/midspace/SEToolbox/releases/download/v1.119.005.1/SEToolbox-01.119.005.1.zip
https://github.com/midspace/SEToolbox/releases/download/v1.119.005.1/SEToolboxSetup-01.119.005.1-en.msi

Did you following our Installation guide?
https://github.com/midspace/SEToolbox/wiki/Installation

**Comment by Amberyl56** [comment]
I have windows 7 Ultimate x64 bit, hit the desktop icon to start it and after a few minutes it says program not responding. 

----- Original Message -----

**Comment by midspace** [comment]
SEToolbox does not create a desktop icon.

Did you download the .zip or the .msi file?
https://github.com/midspace/SEToolbox/releases/download/v1.119.005.1/SEToolbox-01.119.005.1.zip
https://github.com/midspace/SEToolbox/releases/download/v1.119.005.1/SEToolboxSetup-01.119.005.1-en.msi

Did you following our Installation guide?
https://github.com/midspace/SEToolbox/wiki/Installation

**Comment by Amberyl56** [comment]
I made a desktop shortcut for it...followed the instructions and still nothing...using both of the files 


----- Original Message -----

**Comment by midspace** [comment]
I have reviewed the steps for running SEToolbox for the first time.

Could you please tell me how far it got in the steps before it stopped responding?
https://github.com/midspace/SEToolbox/wiki/Installation#running-space-engineers-toolbox-the-first-time

**Comment by Amberyl56** [comment]
I started it up, the splash screen comes up...and sits there....the following is what windows is saying 
Description: 
A problem caused this program to stop interacting with Windows. 
Sorry for all the problems, just upgraded to win 7 64bit and still learning.... 
Thanks for the all help 
Sherrie 

Problem signature: 
Problem Event Name: AppHangB1 
Application Name: SEToolbox.exe 
Application Version: 1.119.5.1 
Application Timestamp: 56a9c036 
Hang Signature: 8401 
Hang Type: 0 
OS Version: 6.1.7601.2.1.0.256.1 
Locale ID: 1033 
Additional Hang Signature 1: 84012f2161be7099c660a9e044f52c17 
Additional Hang Signature 2: c28f 
Additional Hang Signature 3: c28f8f057a5441db81ec914108cdd1ed 
Additional Hang Signature 4: 8401 
Additional Hang Signature 5: 84012f2161be7099c660a9e044f52c17 
Additional Hang Signature 6: c28f 
Additional Hang Signature 7: c28f8f057a5441db81ec914108cdd1ed 

Read our privacy statement online: 
http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409 

If the online privacy statement is not available, please read our privacy statement offline: 
C:\Windows\system32\en-US\erofflps.txt 




----- Original Message -----

**Comment by midspace** [comment]
Is this the actual message from windows, or part of your text? :astonished: 

> the following is what windows is saying Description:

> A problem caused this program to stop interacting with Windows.
> Sorry for all the problems, just upgraded to win 7 64bit and still learning....
> Thanks for the all help
> Sherrie


Okay, these steps I've copied and pasted from another forum, but they represent the issue at hand. A corruption of some sort to the operating system is the usual fault of this sort of error. Either by windows itself, malware, virus, the harddrive, or just something out of place.

<hr/>
Make sure your windows is up-to-date, with the latest Service Patches and security updates.

things you need to do to try and fix this..
 
First rule this out :/
http://www.microsoft.com/security/pc-security/malware-removal.aspx
 
Second make sure windows is not the issue...
 
Test your windows for errors
This works in all windows O/S vista Win7, Win8 and Win8.1 windows system file checker :] Copy and past this to note pad and put it on your desktop. As open programs can give you errors when you run this.

...... sfc /scannow ..... ever hear of it if not your going to love this .... it will inspect all the important windows files as well as the windows DLL files. If windows system file checker finds any issues with the windows files and windows DLL files it will replace them. This little tool as well as the event viewer saved me and fully helped me fix my BF4 issues as well as saved my .... many a format since I found it. This is the best toy they ever put in windows :]

For win7 go to start left click in search type cmd and right click cmd pick run as admin

For win 8.1 right click start bottom left of screen and pick command prompt admin

1 - Open administrator command prompt and close web pages and programs like origin.

2 - Type or copy and paste in sfc /scannow and hit enter, This takes 5 min to 15 min SSD vs HD

3 - This can go one of a few ways ..... no errors ... it fixed some errors ..... could not fix all errors...... does not finish checking and errors out ....... and the last one could not fix errors at all :/

4 -After its done reboot and do it again even if you had no errors the first time or had errors, could not fix ... run sfc /scannow again and when its done a second time reboot. You need to do this a and get no errors 2 x in a row ...

5- So if you ran it 2x and no errors your safe you can stop now for now lol, If you had errors first time but not the second then run sfc /scannow again and when its done reboot. You need to get could not find any errors 2 x to be safe. If it still finds errors try and run it a few more times until it finds no errors 2x AND ALWAYS REBOOT BETWEEN RUNNING sfc /scannow

**Comment by midspace** [comment]
This may or may not be related to recently discovered issue with some free Antivirus application.s
https://github.com/midspace/SEToolbox/wiki/Current-Issues

**Comment by midspace** [comment]
I haven't heard back any response.
Has this issue been resolved ?

**Comment by Amberyl56** [comment]
Sorry I have been sick...yes I have it resolved. Thanks 

----- Original Message -----
