### ISSUE TITLE
since last release have to disable avast to launch it

### ISSUE THREAD

**Issue by yoann217** [midspace/SEToolbox#57]
hello, since release "SEToolbox 01.126.003 Release 1" I have to disable my antivirus avast (free edition) to launch SE toolbox else the avast service just eat my cpu and nothing happen ....

**Comment by midspace** [comment]
I'm unable to provide any support for external applications.
You should contact your antivirus provider directly for support.

Regarding any possibility that the downloadable .zip or .msi package has a virus, you can use the free online tool, www.virustotal.com to scan the url of the download.

Here is a link to the results of scanning the most recent release of SEToolbox in the .zip file.
https://www.virustotal.com/en/url/73417d7ea6e1d65cd1dd74fc7f42cc3728bc777d55423a8ccc3e0c438067d5b5/analysis/1458342234/

**Comment by midspace** [comment]
It appears the only method currently is to add SEToolbox.exe to your Avast exceptions.
http://www.getavast.net/support/managing-exceptions

Again, if you are concerned about SEToolbox containing a virus, Avast themselves recommend using www.virustotal.com to scan the application to verify that it is clean.

**Comment by midspace** [comment]
There is very little more I can do to help with this issue.
From testing, Avast is not flagging SEToolbox as having any sort of virus. It is only taking a very long time to scan the application, and using up an immense amount of CPU to do so.

I can only ask if the more recent version of SEToolbox worked fine.
I have documented this in our wiki under known issues.
https://github.com/midspace/SEToolbox/wiki/Current-Issues
Otherwise I will close this issue.
