### ISSUE TITLE
setoolbox 1.26.003  wont run

### ISSUE THREAD

**Issue by shadow250** [midspace/SEToolbox#58]
i tried upgrading it with the .msi and the zip.also tried deleting the directory and installing both ways.
all it does is lock up my system. i double click the toolbox icon and the busy icon shows until it locks up and i have to press reset.  the 1.25 will launch but wont work because the libraries are outdated.

edit:  i saw the post #57 and it is this. thanks yoann217 :+1:

**Comment by midspace** [comment]
Could you please confirm which version of Windows, and Anti virus you are running?

**Comment by shadow250** [comment]
its win 7 ultimate 64 bit. and avast free antivirus. i put an exception in avast to ignore setoolbox.exe for scanning.

**Comment by theCalcaholic** [comment]
I had the same problem. 
I think it would be a good idea to add this to the FAQ or issues in the Docu.
Otherwise great work! ;)

**Comment by Goobstank** [comment]
almost same issue... was running Panda AV and it locked it down really fast... I uninstalled panda and dont have any other Active AV running SEToolbox still wont open. just hangs. It makes a nice hopeful taskbar icon. Says "SE Toolbox - ()"  thats it... my computer never hung up either.

**Comment by shootingtarget7** [comment]
Having the same problem here.  I try to start the application and it just locks my system up forcing a hard restart.  WIN10 PRO with Avast AV

**Comment by midspace** [comment]
There is very little more I can do to help with this issue.
I have documented this in our wiki under known issues.
https://github.com/midspace/SEToolbox/wiki/Current-Issues

If it continues to be a problem, I can only suggest you individually submit the SEToolbox application to your Antivirus providers as a false positive, and have them more thoroughly check it with their testing tools.
Otherwise I will close this issue.
