### ISSUE TITLE
Locate Application Problem

### ISSUE THREAD

**Issue by emaylo13** [midspace/SEToolbox#78]
Server App Version: 01_144_011 stable
SEToolbox-01.144.000.0.STABLE

![se_toolbox_error](https://cloud.githubusercontent.com/assets/13366876/18329179/87796c38-7552-11e6-96d4-bad974f422a0.jpg)

Continue button disabled, no error message. All is up to date. No white space in path.

Can you fix it ?

**Comment by midspace** [comment]
It looks like there is a minor dependency oversight in the public (stable) branch of the game, which has been fixed in the upcoming Develop branch.

Sorry, the only quick workaround for you, is to copy the `VRage.Render11.dll` file from your game's `Bin64` directory to the `DedicatedServer64` directory.
This will allow SEToolbox to work.

**Comment by emaylo13** [comment]
This temporary solution working good.

Thanks for your answer.

**Comment by scorpnoire** [comment]
Workaround works well. Thank you for the quick help.
