### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by matthew57778** [midspace/SEToolbox#79]
Trojan:Win32/Fethar.B1cl - Severe - 9/11/2016

Category: Trojan

Description: This program is dangerous and executes commands from an attacker.

Recommended action: Remove this software immediately.

Items:
file:D:\GAME ISOS\Space Engineers\SEToolbox\SEToolbox.exe

**Comment by matthew57778** [comment]
Is this a false positive?

**Comment by midspace** [comment]
Whilst I do not put code into SEToolbox that is of malicious nature, this is part of why it is open source, so that anyone can verify and check it. It is also possible for any application to be infected by a virus after installation. That is the purpose of a virus after all. If it is not infected, then it is most likely a false positive.

I do strongly suggest scanning your system for virii and other malware in case it was infected on your computer system to verify that infection did not occur on your computer.

If you have concerns about the SEToolbox distribution been infected you can see the following wiki article on related to Avast Antivirus having issues, and how to scan files on the internet prior to downloading.
https://github.com/midspace/SEToolbox/wiki/Current-Issues

The following are virus analysis on the current .zip file releases which indicate they are both clean.

SEToolbox-01.144.000.0.STABLE.zip
https://www.virustotal.com/en/url/9a431c255a69f96639ced507789429d6226d94fd5981db2f45bc25819dbf625c/analysis/1473634994/

SEToolbox-01.144.000.0.DEVELOP.zip
https://www.virustotal.com/en/url/7aa9c8ac50d00c8874a6098472af50b36a54c3581c2b4c966b80c46bfccf92e7/analysis/1473635068/

**Comment by midspace** [comment]
I have not heard back from @matthew57778 for 19 days regarding the reply above.
Does it satisfactorily answer your concerns?

**Comment by matthew57778** [comment]
Sorry for late response i didn't get a notification for a reply and yes
it's fine to call clean.
