### ISSUE TITLE
SEToolbox stopped working after recent auto-update, now detected as virus by Kaspersky AV

### ISSUE THREAD

**Issue by Reg-Ed** [midspace/SEToolbox#90]
After the most recent autoupdate, SEToolbox stopped working, (it threw an error on launch, I'm afraid I can't remember the exact error and cannot replicate it now).

Accordingly, I deleted the entire SEToolbox directory and downloaded the latest version from GitHub.  When I extracted the files, Kaspersky AV warned me that SEToolbox.exe was 'Dangerous:Multi.Generic'.  When I try to launch SEToolbox, I get a 'Windows cannot access the specified device' error and Kaspersky detects the application as 'PDM:Trojan.Win32.Bazon.a'.

I'm sure this is a false positive and the access error is caused by Kaspersky stopping the file from being loaded, but naturally I'm reluctant to add it to the exclusion list.  SEToolbox has never triggered my AV before so I'm wondering why it does now, and can anything be done about it?

**Comment by midspace** [comment]
This sounds a bit strange, considering I haven't updated SEToolbox for 20 days.

At the moment, all I can suggest is deleting whatever you have downloaded, and downloading a fresh copy directly from the latest release:
https://github.com/midspace/SEToolbox/releases/latest

Some antivirus in the past have been known to have a false positive on SEToolbox. I have more details here on using an online product to scan the SEToolbox release prior to downloading.
https://github.com/midspace/SEToolbox/wiki/Current-Issues

Here is a copy of the virustotal report on the latest release zip file.
https://www.virustotal.com/en/url/556e9cccf758f65c73527d7bb1783ef1db2f7c4244423d6d3d0cba2cb70ef6fd/analysis/1486931517/

**Comment by Reg-Ed** [comment]
Hi Midspace,  thanks for the reply.

I had already done what your instructions suggested (downloading a fresh copy of the latest version) and it was this that was triggering Kaspersky.  I'm not sure what's changed (perhaps a Virus Database update) but KAV no longer seems to be triggered by SEToolbox.  I will post again here if the situation changes.

I do appreciate that this is a problem with the AV, not your software.  I figured you'd want to be aware of the situation nonetheless.

Regards,

Reg_Ed

**Comment by killthrush** [comment]
I've submitted this version to Kaspersky Support as a false positive.  Like you guys, I think this was triggered by a recent virus def update and doesn't have anything to do with the SEToolbox code.

**Comment by m70atkinson** [comment]
Still getting issues detected by Kaspersky.    - Detected UDS:DangerousObject.Multi.Generic with setoolbox.exe.

**Comment by midspace** [comment]
I have submitted a false positive report to the Kaspersky Virus Desk.
They will review the file.
https://virusdesk.kaspersky.com/

**Comment by midspace** [comment]
I've been investigating further, and it appears what I need to do is get a Code Signing Certificate and apply it to SEToolbox.
This will allow AntiVirus applications to trust the SEToolbox.exe, instead of applying all anti-virus routines and heuristics and assuming the worst.

It appears to be a little difficult to get a Code Signing Certificate.
Typically they are for Companies, and cost a chunk of money. And there are checks that are carried out on the Company, I'm assuming to make sure it is legitimate.

Personal Code Signing Certificates seem to be non-existent. There is one group which is free, but they are not trusted by default in the Root authority (which requires users to import the public certificate into their browser). It's a weird arrangement.
Another company is charging a smaller fee for a limited certificate, and requires lots of personal documentation.

At the moment I'm considering getting an Enterprise code signing certificate from Comodo. It appears I have received just enough donations to cover the cost of a 1 year certificate. However I'm trying to figure out if there are any issues with an individual applying for Enterprise certificate and what information I may need to present.

**Comment by midspace** [comment]
If you have noticed, I have gone ahead with a new build and release.
https://github.com/midspace/SEToolbox/releases/latest

There were only 2 minor changes in the code.
The virustotal scans showing no malware or virus detections. I don't think the changes contributed to this, but as far as I know there is basically no difference between this, and the previous release.

I'm going to lessen my effort to look for a code signing certificate at this point.
I'm told that SESE and SEWT (se workshop tool) don't have any code signing and haven't run into any issues with anti virus.

**Comment by krytie75** [comment]
Good to hear, midspace.  It would be a shame for you to have to put resources into getting a certificate on account of a couple of mis-detections by AV software.  Unfortunately I can't test the new release on my server at the moment but will let you know if I encounter any problems when I get the chance.

**Comment by m70atkinson** [comment]
I just downloaded the new version and Kaspersky didn't complain about a
virus.  Nice work.

Thanks for all your efforts.

Mark

**Comment by killthrush** [comment]
Same here, version 01.179.001.1took care of the kaspersky false positive for me.  Well done!  Sorry I had no luck with submitting a report - they gave me the runaround and closed the ticket without a resolution.

**Comment by midspace** [comment]
I'm closing this issue for now.
So far the Anti-Virus companies are playing nice since the last release on April 11 (a month ago) and there hasn't been any false positive detections.
