### ISSUE TITLE
[1.181.1.1] Error on launch

### ISSUE THREAD

**Issue by everwake242** [midspace/SEToolbox#99]
the initial update fails, when choosing to launch anyway the error says it cannot find the file VRage.Math, version 1.0.0.0, Culture= neutral, PublicKeyToken=null. I cannot see any log file being produced

I have tested both the msi and the zip on a fresh install of windows 10

edit: tried 1.179 with the same result so it seem like a general issue for me

Edit 2: figured out the issue, I answer the UAC with a domain admin account, my normal user is not an admin on my PC, this does not work, if I start a command prompt as the same domain admin, and launch SEtoolbox from that command line, then it works

**Comment by midspace** [comment]
UAC is required any time SEToolbox needs to update.
Security in Windows 8 and 10 prevents the copying of files to the "C:\Program Files" or "C:\Program Files (x86)" directories without UAC.
These files are some of the Space Engineers files that the Toolbox needs in order to run.

I wish there was a way to avoid doing this.
I had tried a method where SEToolbox copies the files to the temporary directory and uses them there, but some computer systems would not work with this setup and it was impossible to tell why it failed.
